TEXT_UPDATES_NEVER = 0
TEXT_UPDATES_ALWAYS = 1
TEXT_UPDATES_SOMETIMES = 2
TEXT_UPDATES_MAYBE = 3

TEXT_UPDATE_CHOICES = (
    (TEXT_UPDATES_ALWAYS, 'Yes, every time'),
    (TEXT_UPDATES_SOMETIMES, 'Yes, on some trips'),
    (TEXT_UPDATES_MAYBE, 'Not sure'),
    (TEXT_UPDATES_NEVER, 'No'),
)
