# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('display_name', models.CharField(blank=True, max_length=128, null=True)),
                ('unlimited_rides', models.BooleanField(default=False)),
                ('included_rides_per_month', models.PositiveSmallIntegerField(help_text='Number of rides included in plan. Enter 0 for unlimited rides.')),
                ('ride_distance_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Limit, in miles, of rides included in this plan.', max_digits=6, null=True)),
                ('monthly_cost', models.DecimalField(blank=True, decimal_places=2, help_text='The monthly subscription fee for this plan.', max_digits=6, null=True)),
                ('arrive_fee', models.DecimalField(blank=True, decimal_places=2, help_text='The Arrive surcharge added to rides not included in the plan.', max_digits=6, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
