# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='arrive_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The Arrive surcharge added to rides not included in the plan, in dollars.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='included_rides_per_month',
            field=models.PositiveSmallIntegerField(help_text='Number of rides per month included in plan. Additional rides will be billed to customer.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='monthly_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The monthly subscription fee for this plan, in dollars.', max_digits=6, null=True),
        ),
    ]
