# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20161127_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='included_rides_per_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of rides per month included in plan. Additional rides will be billed to customer.', null=True),
        ),
    ]
