# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20161127_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('stripe_id', models.CharField(max_length=255)),
                ('last_4_digits', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
