# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20161127_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='stripe_id',
            new_name='stripe_token',
        ),
    ]
