# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_plan_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='stripe_token',
            new_name='stripe_id',
        ),
    ]
