# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20161129_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='signup_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='A one-time fee charged on signup. Not required.', max_digits=6, null=True),
        ),
    ]
