# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_auto_20170103_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
