# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_plan_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('display_name', models.CharField(blank=True, max_length=128, null=True)),
                ('active', models.BooleanField(default=True)),
                ('includes_ride_cost', models.BooleanField(default=False)),
                ('includes_arrive_fee', models.BooleanField(default=False)),
                ('includes_signup_cost', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_membership', to='billing.Plan')),
                ('ride_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride_group_plan', to='billing.StripeCustomer')),
                ('subscription_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_group_plan', to='billing.StripeCustomer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
