# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_groupmembership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmembership',
            old_name='includes_signup_cost',
            new_name='includes_subscription',
        ),
    ]
