# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_auto_20170325_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='bill_online',
            field=models.BooleanField(default=False),
        ),
    ]
