# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-03 17:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0017_groupmembership_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user_created', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.Balance'),
        ),
    ]
