# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-10 22:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0029_auto_20171107_1556'),
        ('billing', '0017_groupmembership_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user_created', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_date', models.DateField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.Balance')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='after_hours_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=7.0, help_text='The surcharge added to rides scheduled outside business hours.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer'),
        ),
    ]
