# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-05 05:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0033_auto_20180104_2029'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0018_auto_20171124_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rides.Destination'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='residence_type',
            field=models.CharField(choices=[(None, b''), (b'AP', b'Apartment'), (b'AL', b'Assisted Living Facility'), (b'RT', b'Retirement Community'), (b'SF', b'Single Family Home'), (b'SN', b'Skilled Nursing Facility')], default=b'RT', max_length=2),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
