# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-13 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_remove_customer_balance'),
        ('billing', '0018_auto_20171110_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='balance',
        ),
        migrations.AddField(
            model_name='balance',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gift',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
