# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-10 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_auto_20171103_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='after_hours_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=7.0, help_text='The surcharge added to rides scheduled outside business hours.', max_digits=6, null=True),
        ),
    ]
