# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-25 20:24
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_auto_20180104_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='phone',
            field=localflavor.us.models.PhoneNumberField(blank=True, null=True),
        ),
    ]
