# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-14 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_auto_20171113_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='stripe_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.StripeCustomer'),
        ),
    ]
