# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-02 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_groupmembership_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='default_user_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='bill_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='includes_arrive_fee',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='includes_ride_cost',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='includes_subscription',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='plan',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='group_membership', to='billing.Plan'),
        ),
    ]
