# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-06-03 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_auto_20180201_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='after_hours_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=5.0, help_text='The surcharge added to rides scheduled outside business hours.', max_digits=6, null=True),
        ),
    ]
