# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('street1', models.CharField(blank=True, max_length=100, null=True)),
                ('street2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', localflavor.us.models.USStateField(blank=True, null=True)),
                ('zip_code', localflavor.us.models.USZipCodeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='U.S.A.', max_length=100, null=True)),
                ('phone', localflavor.us.models.PhoneNumberField(blank=True, null=True)),
            ],
        ),
    ]
