# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='touch',
            options={'verbose_name': 'Touch', 'verbose_name_plural': 'Touches'},
        ),
    ]
