# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-12 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0006_auto_20171103_1053'),
        ('concierge', '0006_auto_20170920_1548'),
    ]

    operations = [
    ]
