# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('known_as', models.CharField(blank=True, max_length=50, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('spent_to_date', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('residence_type', models.CharField(choices=[('AP', 'Apartment'), ('AL', 'Assisted Living Facility'), ('RT', 'Retirement Community'), ('SF', 'Single Family Home'), ('SN', 'Skilled Nursing Facility')], default='SF', max_length=2)),
                ('residence_instructions', models.TextField(blank=True, null=True)),
                ('special_assistance', models.CharField(blank=True, max_length=1024, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LovedOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('street1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1')),
                ('street2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', localflavor.us.models.USStateField(blank=True, null=True)),
                ('zip_code', localflavor.us.models.USZipCodeField(blank=True, null=True, verbose_name='ZIP')),
                ('country', models.CharField(blank=True, default='U.S.A.', max_length=100, null=True)),
                ('phone', localflavor.us.models.PhoneNumberField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('text_updates', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
