# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='home',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.Location'),
        ),
        migrations.AlterField(
            model_name='lovedone',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.Location'),
        ),
    ]
