# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161106_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='notes',
            field=models.TextField(blank=True, help_text="e.g., 'Customer is hard of hearing, please speak up.'", null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='residence_instructions',
            field=models.TextField(blank=True, help_text="e.g., 'Buzz #2 at gate'", null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='special_assistance',
            field=models.CharField(blank=True, help_text="e.g., 'Customer uses walker, please store in trunk'", max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lovedone',
            name='name',
            field=models.CharField(blank=True, help_text='e.g., Dunder Mifflin Scranton', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lovedone',
            name='street1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='lovedone',
            name='street2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='lovedone',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(blank=True, null=True, verbose_name='ZIP'),
        ),
    ]
