# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161106_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='residence_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='special_assistance',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lovedone',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
