# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 00:27
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20161114_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='lovedone',
            name='mobile_phone',
            field=localflavor.us.models.PhoneNumberField(blank=True, null=True),
        ),
    ]
