# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_lovedone_mobile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='receive_updates',
            field=models.BooleanField(default=False),
        ),
    ]
