# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_receive_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='residence_type',
            field=models.CharField(choices=[(None, ''), ('AP', 'Apartment'), ('AL', 'Assisted Living Facility'), ('RT', 'Retirement Community'), ('SF', 'Single Family Home'), ('SN', 'Skilled Nursing Facility')], default='SF', max_length=2),
        ),
    ]
