# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20161127_1653'),
        ('accounts', '0009_auto_20161117_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.Plan'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ride_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ride_customer', to='billing.StripeCustomer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='subscription_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_customer', to='billing.StripeCustomer'),
        ),
    ]
