# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20161127_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
