# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
