# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20161206_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='intro_call',
            field=models.BooleanField(default=False),
        ),
    ]
