# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customer_intro_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
