# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customer_contact_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact_on',
            new_name='gift_date',
        ),
    ]
