# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20161213_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_ride',
        ),
    ]
