# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 21:56
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_customer_last_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=localflavor.us.models.PhoneNumberField(blank=True, null=True),
        ),
    ]
