# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_customer_send_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='send_updates',
            field=models.BooleanField(default=False),
        ),
    ]
