# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_customer_preferred_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='timezone',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
