# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_customer_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, default=b'America/Los_Angeles', max_length=128, null=True),
        ),
    ]
