# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_groupmembership'),
        ('accounts', '0023_userprofile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='group_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.GroupMembership'),
        ),
    ]
