# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-16 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_lovedone_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='source_specific',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
