# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-01 03:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
