# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-10 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_auto_20171110_1437'),
        ('accounts', '0029_auto_20171107_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.Balance'),
        ),
    ]
