# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-28 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20171124_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this customer should be treated as active.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='plan',
            field=models.ForeignKey(blank=True, default=8, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.Plan'),
        ),
    ]
