# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-12 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_customer_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='balance',
        ),
    ]
