# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-04 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20171128_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_group_admin',
            field=models.BooleanField(default=False),
        ),
    ]
