# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-12 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20170920_1548'),
        ('accounts', '0031_auto_20171128_1205'),
    ]

    operations = [
    ]
