# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('street1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1')),
                ('street2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', localflavor.us.models.USStateField(blank=True, null=True)),
                ('zip_code', localflavor.us.models.USZipCodeField(blank=True, null=True, verbose_name='ZIP')),
                ('country', models.CharField(blank=True, default='U.S.A.', max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('home', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_point', to='rides.Destination')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_point', to='rides.Destination')),
            ],
        ),
    ]
