# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='address',
        ),
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.CharField(blank=True, default='U.S.A.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='phone',
            field=localflavor.us.models.PhoneNumberField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='street1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='street2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(blank=True, null=True),
        ),
    ]
