# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20161108_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='lattitude',
        ),
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
