# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_auto_20161122_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_point', to='rides.Destination', verbose_name='Starting point'),
        ),
    ]
