# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_auto_20161123_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
