# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_auto_20161123_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='service',
            field=models.CharField(blank=True, choices=[(b'Uber', b'Uber'), (b'Lyft', b'Lyft')], default=b'Lyft', max_length=64, null=True),
        ),
    ]
