# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_ride_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='request_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
