# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_auto_20161206_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
