# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0011_ride_fare_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
