# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_ride_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='included_in_plan',
            field=models.BooleanField(default=False),
        ),
    ]
