# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_ride_included_in_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='fare_estimate',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
