# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0014_auto_20161221_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='invoice_item_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
