# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_invoice'),
        ('rides', '0015_auto_20161221_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='invoiced',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='invoiced_date',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='paid_date',
        ),
        migrations.AddField(
            model_name='ride',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='billing.Invoice'),
        ),
    ]
