# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0016_auto_20170103_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='ride',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ride',
            name='service',
            field=models.CharField(blank=True, choices=[(b'Uber', b'Uber'), (b'Lyft', b'Lyft')], default=b'Uber', max_length=64, null=True),
        ),
    ]
