# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0017_auto_20170111_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ending_point', to='rides.Destination'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting_point', to='rides.Destination', verbose_name='Starting point'),
        ),
    ]
