# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0018_auto_20170201_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='included_in_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
