# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0019_auto_20170201_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='service',
            new_name='company',
        ),
    ]
