# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0020_auto_20170206_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='company',
            field=models.CharField(blank=True, choices=[(b'Uber', b'Uber'), (b'Lyft', b'Lyft')], max_length=64, null=True),
        ),
    ]
