# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-17 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0021_auto_20170213_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
