# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-08 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0023_auto_20170217_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='timezone',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
