# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-24 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0024_destination_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='rider',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
