# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-20 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0026_destination_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='accounts.Customer'),
        ),
    ]
