# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-01 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0027_auto_20170520_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='ride',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
