# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-01 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0028_auto_20170701_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='cancelled_reason',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
