# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-12 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0033_auto_20180104_2029'),
        ('rides', '0031_auto_20170920_1615'),
    ]

    operations = [
    ]
