# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-06-03 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0035_destinationattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationattachment',
            options={'ordering': ['-uploaded_date']},
        ),
    ]
